[general]
import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
]

[window]
padding.x = 5
padding.y = 5
decorations = "Buttonless"
opacity = 0.9 
option_as_alt = "Both"

[font]
normal.family = "JetBrains Mono NL"
size = 18

[cursor]
style = { shape = "Beam", blinking = "Off" }
