# ============================================================
# General
# ============================================================

# Start indexing windows/panes from 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when one is closed
set -g renumber-windows on

# Enable mouse
set -g mouse on

# Increase scrollback
set -g history-limit 10000

# Allow tmux to use true color
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# use C-a and C-space for the prefix.
set-option -g prefix C-a
set-option -g prefix2 C-space
unbind-key C-a
bind-key C-space send-prefix

# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# ============================================================
# Pane Creation
# ============================================================

# Split panes in the current directory
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Unbind the default split keys
unbind %
unbind '"'

# ============================================================
# Pane Navigation
# ============================================================

# Vim-style navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# ============================================================
# Window Management
# ============================================================

# windows Creation
unbind c
bind n new-window -c "#{pane_current_path}"

# Switch windows with Shift+Arrow 
bind -n S-Left  previous-window
bind -n S-Right next-window

# Reorder windows with CTRL+SHIFT+Arrow
bind-key -n C-S-Left swap-window -t -1 \; select-window -t -1
bind-key -n C-S-Right swap-window -t +1 \; select-window -t +1

# ============================================================
# Status Bar
# ============================================================

set -g status-position bottom
set -g status-interval 60

set -g status-left-length 30
set -g status-right-length 60

set -g status-left " #S "
set -g status-right "#[bg=colour36] 🕔 #[fg=colour234]%H:%M "

setw -g window-status-format " #I: #W "
setw -g window-status-current-format " *#I: #W "

set -g status-bg "black"
set -g status-fg "color67"

# setw -g window-status-style "fg=colour67,bg=black"
setw -g window-status-current-style "fg=black,bg=colour36"


# ============================================================
# Session Management
# ============================================================

unbind C-c
bind N new-session
