# git
alias lg="lazygit"
alias gst="git status"
alias ga="git add"
alias gaa="git add ."
alias gc="git commit"
alias gp="git push"
alias gco="git checkout"
alias gb="git branch"
alias gd="git diff"
alias gcp="git cherry-pick"
alias gl="git log"
alias gf="git fetch"
alias grhh="git reset --hard"
alias grb="git rebase"
alias g="git"

# other useful
alias y="yazi"
alias zshconfig="nvim ~/.zshrc"
alias reload="source ~/.zshrc"
alias battery="pmset -g batt"
alias rg="rg --hyperlink-format=kitty"
